export const noteSkat = [
    { value: 'glukhoi', label: 'Глухой' },
    { value: 'vitrina', label: 'Витрина' },
    { value: 'vitrina_s_vyborkoi', label: 'Витрина с выборкой' },
    { value: 'vitrina_4_okoshka', label: 'Витрина 4 окошка' },
    { value: 'vitrina_6_okoshka', label: 'Витрина 6 окошек' },
    { value: 'vitrina_8_okoshka', label: 'Витрина 8 окошек' },
    { value: 'fasad_figurnyi_glukhoi', label: 'Фасад фигурный глухой' },
    { value: 'fasad_figurnyi_vitrina', label: 'Фасад фигурный витрина' },
    { value: 'fasad_figurnyi_vitrina_s_reshetkoi', label: 'Фасад фигурный витрина с решеткой' },
    { value: 'fasad_arochnyi_tip_1_glukhoi', label: 'Фасад арочный ТИП 1 глухой' },
    { value: 'fasad_arochnyi_tip_2_glukhoi', label: 'Фасад арочный ТИП 2 глухой' },
    { value: 'fasad_arochnyi_tip_1_vitrina', label: 'Фасад арочный ТИП 1 витрина' },
    { value: 'fasad_arochnyi_tip_2_vitrina', label: 'Фасад арочный ТИП 2 витрина' },
    { value: 'fasad_arochnyi_tip_1_vitrina_s_reshetkoi', label: 'Фасад арочный ТИП 1 витрина с решеткой' },
    { value: 'fasad_arochnyi_tip_2_vitrina_s_reshetkoi', label: 'Фасад арочный ТИП 2 витрина с решеткой' },
    { value: 'vitrina_tip_2', label: 'Витрина ТИП 2' },
    { value: 'vitrina_tip_3', label: 'Витрина ТИП 3' },
    { value: 'vitrina_tip_4', label: 'Витрина ТИП 4' },
    { value: 'vitrina_tip_5', label: 'Витрина ТИП 5' },
    { value: 'vitrina_tip_6_levaya', label: 'Витрина ТИП 6 левая' },
    { value: 'vitrina_tip_6_pravaya', label: 'Витрина ТИП 6 правая' },
    { value: 'vitrina_tip_7', label: 'Витрина ТИП 7' },
    { value: 'vitrina_setka_1', label: 'Витрина сетка №1' },
    { value: 'vitrina_setka_2', label: 'Витрина сетка №2' },
    { value: 'vitrina_setka_3', label: 'Витрина сетка №3' },
    { value: 'vitrina_setka_4', label: 'Витрина сетка №4' },
    { value: 'vitrina_setka_5', label: 'Витрина сетка №5' },
    { value: 'vitrina_s_diagonalnoi_reshetkoi_1_okno', label: 'Витрина с диагональной решеткой 1 окно' },
    { value: 'vitrina_s_diagonalnoi_reshetkoi_2_okna', label: 'Витрина с диагональной решеткой 2 окна' },
    { value: 'vitrina_s_diagonalnoi_reshetkoi_3_okna', label: 'Витрина с диагональной решеткой 3 окна' },
    { value: 'vitrina_s_diagonalnoi_reshetkoi_4_okna', label: 'Витрина с диагональной решеткой 4 окна' },
    { value: 'poluvitrina_po_risunku', label: 'Полувитрина по рисунку' },
    { value: 'left', label: 'Левый' },
    { value: 'right', label: 'Правый' },
    { value: 'tonkaya_freza', label: 'Тонкая фреза' },
    { value: 'bez_frezy_po_fasadu', label: 'без фрезы по фасаду' },
    { value: 'bez_frezy_po_fasadu_po_krayu_0', label: 'без фрезы по фасаду, по краю №0' },
    { value: 'bez_frezy_po_fasadu_po_krayu_1', label: 'без фрезы по фасаду, по краю №1' },
    { value: 'bez_frezy_po_fasadu_po_krayu_2', label: 'без фрезы по фасаду, по краю №2' },
    { value: 'bez_frezy_po_fasadu_po_krayu_3', label: 'без фрезы по фасаду, по краю №3' },
    { value: 'bez_frezy_po_fasadu_po_krayu_011', label: 'без фрезы по фасаду, по краю №011' },
    { value: 'bez_frezy_po_fasadu_po_krayu_012', label: 'без фрезы по фасаду, по краю №012' },
    { value: 'bez_frezy_po_fasadu_po_krayu_022', label: 'без фрезы по фасаду, по краю №022' },
    { value: 'bez_frezy_po_fasadu_po_krayu_033', label: 'без фрезы по фасаду, по краю №033' },
    { value: 'bez_frezy_po_fasadu_po_krayu_044', label: 'без фрезы по фасаду, по краю №044' },
    { value: 'bez_frezy_po_fasadu_po_krayu_f3', label: 'без фрезы по фасаду, по краю №Ф3' },
    { value: 'bez_frezy_po_fasadu_po_krayu_f5', label: 'без фрезы по фасаду, по краю №Ф5' },
    { value: 'bez_frezy_po_fasadu_po_krayu_f8', label: 'без фрезы по фасаду, по краю №Ф8' },
    { value: 'bez_frezy_po_fasadu_po_krayu_45', label: 'без фрезы по фасаду, по краю №45' },
    { value: 'bez_frezy_po_fasadu_po_krayu_minimalnyi', label: 'без фрезы по фасаду, по краю минимальный' },
    { value: 'bez_frezy_po_fasadu_po_krayu_ugol_90', label: 'без фрезы по фасаду, по краю угол 90' },
    { value: 'po_krayu_0', label: 'по краю №0' },
    { value: 'po_krayu_1', label: 'по краю №1' },
    { value: 'po_krayu_2', label: 'по краю №2' },
    { value: 'po_krayu_3', label: 'по краю №3' },
    { value: 'po_krayu_011', label: 'по краю №011' },
    { value: 'po_krayu_012', label: 'по краю №012' },
    { value: 'po_krayu_022', label: 'по краю №022' },
    { value: 'po_krayu_033', label: 'по краю №033' },
    { value: 'po_krayu_044', label: 'по краю №044' },
    { value: 'po_krayu_f3', label: 'по краю №Ф3' },
    { value: 'po_krayu_f5', label: 'по краю №Ф5' },
    { value: 'po_krayu_f8', label: 'по краю №Ф8' },
    { value: 'po_krayu_45', label: 'по краю №45' },
    { value: 'po_krayu_minimalnyi', label: 'по краю минимальный' },
    { value: 'po_krayu_ugol_90', label: 'по краю угол 90' },
    { value: 'volna_na_ves_fasad', label: 'Волна на весь фасад' },
    { value: 'volna_2_na_ves_fasad', label: 'Волна 2 на весь фасад' },
    { value: 'po_risunku', label: 'по рисунку' },
    { value: 'izgolove', label: 'Изголовье' },
    { value: 'iznozhe', label: 'Изножье' },
    { value: 'butylocznica', label: 'Бутылочница' },
    { value: 'polnocennaya_frezervovka', label: 'Полноценная фрезеровка' },
    { value: 'dveri_dlya_shkafov_tip_1', label: 'Двери для шкафов ТИП 1' },
    { value: 'dveri_dlya_shkafov_tip_2', label: 'Двери для шкафов ТИП 2' },
    { value: 'dveri_dlya_shkafov_tip_3', label: 'Двери для шкафов ТИП 3' },
    { value: 'dveri_dlya_shkafov_tip_4', label: 'Двери для шкафов ТИП 4' },
    { value: 'dveri_dlya_shkafov_poluvitrina_tip_1', label: 'Двери для шкафов Полувитрина ТИП 1' },
    { value: 'dveri_dlya_shkafov_polureshetka_tip_2_var_1', label: 'Двери для шкафов Полурешетка ТИП 2 Вар 1' },
    { value: 'dveri_dlya_shkafov_polureshetka_tip_2_var_2', label: 'Двери для шкафов Полурешетка ТИП 2 Вар 2' },
    { value: 'sbornyi_dveri_dlya_shkafov_tip_1', label: 'Сборный двери для шкафов ТИП 1' },
    { value: 'sbornye_dveri_dlya_shkafov_tip_2', label: 'Сборные двери для шкафов ТИП 2' },
    { value: 'sbornye_dveri_dlya_shkafov_tip_3', label: 'Сборные двери для шкафов ТИП 3' },
    { value: 'sbornye_dveri_dlya_shkafov_tip_4', label: 'Сборные двери для шкафов ТИП 4' },
    { value: 'sbornye_dveri_dlya_shkafov_poluvitrina_tip_1', label: 'Сборные двери для шкафов Полувитрина ТИП 1' },
    { value: 'vstavki_dlya_shkafov-kupe_1', label: 'Вставки для шкафов-купе №1' },
    { value: 'vstavki_dlya_shkafov-kupe_2', label: 'Вставки для шкафов-купе №2' },
    { value: 'vstavki_dlya_shkafov-kupe_3', label: 'Вставки для шкафов-купе №3' },
    { value: 'vstavki_dlya_shkafov-kupe_4', label: 'Вставки для шкафов-купе №4' },
    { value: 'vstavki_dlya_shkafov-kupe_5', label: 'Вставки для шкафов-купе №5' },
    { value: 'vstavki_dlya_shkafov-kupe_6', label: 'Вставки для шкафов-купе №6' },
    { value: 'vstavki_dlya_shkafov-kupe_7', label: 'Вставки для шкафов-купе №7' },
    { value: 'vstavki_dlya_shkafov-kupe_8', label: 'Вставки для шкафов-купе №8' },
    { value: 'vstavki_dlya_shkafov-kupe_9', label: 'Вставки для шкафов-купе №9' },
    { value: 'vstavki_dlya_shkafov-kupe_10', label: 'Вставки для шкафов-купе №10' },
    { value: 'vstavki_dlya_shkafov-kupe_11', label: 'Вставки для шкафов-купе №11' },
    { value: 'vstavki_dlya_shkafov-kupe_12', label: 'Вставки для шкафов-купе №12' },
    { value: 'vstavki_dlya_shkafov-kupe_13', label: 'Вставки для шкафов-купе №13' },
    { value: 'vstavki_dlya_shkafov-kupe_14', label: 'Вставки для шкафов-купе №14' },
    { value: 'vstavki_dlya_shkafov-kupe_15', label: 'Вставки для шкафов-купе №15' },
    { value: 'vstavki_dlya_shkafov-kupe_16', label: 'Вставки для шкафов-купе №16' },
    { value: 'vstavki_dlya_shkafov-kupe_17', label: 'Вставки для шкафов-купе №17' },
    { value: 'vstavki_dlya_shkafov-kupe_18', label: 'Вставки для шкафов-купе №18' },
    { value: 'vstavki_dlya_shkafov-kupe_19', label: 'Вставки для шкафов-купе №19' },
    { value: 'vstavki_dlya_shkafov-kupe_20', label: 'Вставки для шкафов-купе №20' },
    { value: 'vstavki_dlya_shkafov-kupe_21', label: 'Вставки для шкафов-купе №21' },
    { value: 'vstavki_dlya_shkafov-kupe_22', label: 'Вставки для шкафов-купе №22' },
    { value: 'vstavki_dlya_shkafov-kupe_23', label: 'Вставки для шкафов-купе №23' },
    { value: 'vstavki_dlya_shkafov-kupe_24', label: 'Вставки для шкафов-купе №24' },
    { value: 'vstavki_dlya_shkafov-kupe_25', label: 'Вставки для шкафов-купе №25' },
    { value: 'vstavki_dlya_shkafov-kupe_26', label: 'Вставки для шкафов-купе №26' },
    { value: 'vstavki_dlya_shkafov-kupe_27', label: 'Вставки для шкафов-купе №27' },
    { value: 'vstavki_dlya_shkafov-kupe_28', label: 'Вставки для шкафов-купе №28' },
    { value: 'spala_1', label: 'Спала №1' },
    { value: 'spala_2', label: 'Спала №2' },
    { value: 'spala_3', label: 'Спала №3' },
    { value: 'spala_4', label: 'Спала №4' },
    { value: 'spala_5', label: 'Спала №5' },
    { value: 'spala_6', label: 'Спала №6' },
    { value: 'spala_7', label: 'Спала №7' },
    { value: 'spala_8', label: 'Спала №8' },
    { value: 'spala_9', label: 'Спала №9' },
    { value: 'spala_10', label: 'Спала №10' },
    { value: 'spala_11', label: 'Спала №11' },
    { value: 'spala_avrora', label: 'Спала Аврора' },
    { value: 'spala_kanzas', label: 'Спала Канзас' },
    { value: 'spala_malta', label: 'Спала Мальта' },
    { value: 'spala_milan', label: 'Спала Милан' },
    { value: 'spala_monako', label: 'Спала Монако' },
    { value: 'spala_montana', label: 'Спала Монтана' },
    { value: 'spala_praga', label: 'Спала Прага' },
    { value: 'spala_sakura', label: 'Спала Сакура' },
    { value: 'spala_skarlett', label: 'Спала Скарлетт' },
    { value: 'spala_chester', label: 'Спала Честер' },
    { value: 'kosichka_1', label: 'Косичка №1' },
    { value: 'kosichka_2', label: 'Косичка №2' },
    { value: 'kosichka_3', label: 'Косичка №3' },
    { value: 'kosichka_4', label: 'Косичка №4' },
    { value: 'kosichka_5', label: 'Косичка №5' },
    { value: 'kosichka_6', label: 'Косичка №6' },
    { value: 'kosichka_7', label: 'Косичка №7' },
    { value: 'kosichka_8', label: 'Косичка №8' },
    { value: 'kosichka_9', label: 'Косичка №9' },
    { value: 'plenka_s_2h_storon', label: 'Пленка с 2х сторон' },
    { value: 'standartnyi_karniz_1', label: 'Стандартный карниз №1' },
    { value: 'standartnyi_karniz_2', label: 'Стандартный карниз №2' },
    { value: 'integrirovannaya_ruchka', label: 'Интегрированная ручка' },
];

export const noteClassic = [
    { value: 'glukhoiClassic', label: 'Глухой' },
];

export const note4 = [
    { value: 'glukhoi4', label: 'Глухой' },
    { value: 'yummy', label: 'Прямой' },
    { value: 'radius', label: 'Радиусный' },
    { value: 'alramka', label: 'С Алюминиевой рамкой' },
];

export const noteYourDay = [
    { value: 'note-1', label: 'Глухой' },
    { value: 'note-2', label: 'Без фрезеровки' },
    { value: 'note-3', label: 'Витрина' },
    { value: 'note-4', label: 'Витрина с выборкой' },
    { value: 'note-5', label: 'Витрина крест' },
    { value: 'note-6', label: 'Витрина диагональная' },
    { value: 'note-7', label: 'Витрина ромб' },
    { value: 'note-8', label: 'Витрина прямоугольная' },
    { value: 'note-9', label: 'Радиусный R300 вогнутый' },
    { value: 'note-10', label: 'Радиусный R300 выпуклый' },
    { value: 'note-11', label: 'Радиусный R450 вогнутый' },
    { value: 'note-12', label: 'Радиусный R450 выпуклый' },
    { value: 'note-13', label: 'Интегрированная ручка ИР 1 по высоте' },
    { value: 'note-14', label: 'Интегрированная ручка ИР 1 по ширине' },
    { value: 'note-15', label: 'Интегрированная ручка ИР 2 по высоте' },
    { value: 'note-16', label: 'Интегрированная ручка ИР 2 по ширине' },
    { value: 'note-17', label: 'Интегрированная ручка ИР 2.1 по высоте' },
    { value: 'note-18', label: 'Интегрированная ручка ИР 2.1 по ширине' },
    { value: 'note-19', label: 'Интегрированная ручка ИР 2.2 по высоте' },
    { value: 'note-20', label: 'Интегрированная ручка ИР 2.2 по ширине' },
    { value: 'note-21', label: 'Карниз 16мм ' },
    { value: 'note-22', label: 'Карниз 16/2' },
    { value: 'note-23', label: 'Карниз 16/2 с косичкой' },
    { value: 'note-24', label: 'Карниз прямой 30мм' },
    { value: 'note-25', label: 'Карниз прямой c косичкой 30мм' },
    { value: 'note-26', label: 'Карниз выпуклый 30мм' },
    { value: 'note-27', label: 'Карниз вогнутый 30мм' },
    { value: 'note-28', label: 'Карниз выпуклый 30мм с косичкой' },
    { value: 'note-29', label: 'Карниз вогнутый 30мм с косичкой' },
    { value: 'note-30', label: 'Карниз прямой 56мм' },
    { value: 'note-31', label: 'Карниз выпуклый 56мм' },
    { value: 'note-32', label: 'Карниз вогнутый 56мм' },
    { value: 'note-33', label: 'Карниз 56/1, 56/2 прямой' },
    { value: 'note-34', label: 'Карниз 56/1, 56/2 выпуклый' },
    { value: 'note-35', label: 'Карниз 56/1, 56/2 вогнутый' },
    { value: 'note-36', label: 'Декоративная планка 16мм №1 прямая' },
    { value: 'note-37', label: 'Декоративная планка 16мм №2 прямая' },
    { value: 'note-38', label: 'Декоративная планка 16мм №1 выпуклая' },
    { value: 'note-39', label: 'Декоративная планка 16мм №1 вогнутая' },
    { value: 'note-40', label: 'Декоративная планка 16мм №2 выпуклая' },
    { value: 'note-41', label: 'Декоративная планка 16мм №2 вогнутая' },
    { value: 'note-42', label: 'Декоративная планка №3 прямая' },
    { value: 'note-43', label: 'Декоративная планка №3 выпуклая' },
    { value: 'note-44', label: 'Декоративная планка №3 вогнутая' },
    { value: 'note-45', label: 'Декоративная планка №4 прямая' },
    { value: 'note-46', label: 'Декоративная планка №4 выпуклая' },
    { value: 'note-47', label: 'Декоративная планка №4 вогнутая' },
    { value: 'note-48', label: 'Декоративная планка 19мм №1 прямая' },
    { value: 'note-49', label: 'Декоративная планка 19мм №2 прямая' },
    { value: 'note-50', label: 'Декоративная планка 19мм №1 выпуклая' },
    { value: 'note-51', label: 'Декоративная планка 19мм №1 вогнутая' },
    { value: 'note-52', label: 'Декоративная планка 19мм №2 выпуклая' },
    { value: 'note-53', label: 'Декоративная планка 19мм №2 вогнутая' },
    { value: 'note-54', label: 'Балюстрада 16мм №1 1000мм' },
    { value: 'note-55', label: 'Балюстрада 16мм №1 1500мм' },
    { value: 'note-56', label: 'Балюстрада 16мм №2 1000мм ' },
    { value: 'note-57', label: 'Балюстрада 16мм №2 1500мм' },
    { value: 'note-58', label: 'Пилястра №1' },
    { value: 'note-59', label: 'Пилястра №2' },
    { value: 'note-60', label: 'Пилястра №3' },
    { value: 'note-61', label: 'Пилястра №4' },
    { value: 'note-62', label: 'Пилястра №5' },
    { value: 'note-63', label: 'Пилястра №6' },
    { value: 'note-64', label: 'Пилястра №7' },
    { value: 'note-65', label: 'Пилястра №8' },
    { value: 'note-66', label: 'Пилястра №9' },
    { value: 'note-67', label: 'Пилястра №10' },
    { value: 'note-68', label: 'Пилястра №11' },
    { value: 'note-69', label: 'Пилястра №12' },
    { value: 'note-70', label: 'Пилястра №13' },
    { value: 'note-71', label: 'Пилястра №14' },
    { value: 'note-72', label: 'Пилястра №15' },
    { value: 'note-73', label: 'Пилястра №16' },
    { value: 'note-74', label: 'Пилястра №17' },
    { value: 'note-75', label: 'Пилястра №18' },
    { value: 'note-76', label: 'Пилястра №19' },
    { value: 'note-77', label: 'Пилястра №20' },
    { value: 'note-78', label: 'Пилястра №21' },
    { value: 'note-79', label: 'Пилястра №22' },
    { value: 'note-80', label: 'Пилястра №23' },
    { value: 'note-81', label: 'Арка №1' },
    { value: 'note-82', label: 'Арка №2' },
    { value: 'note-83', label: 'Арка №3' },
    { value: 'note-84', label: 'Арка №4' },
    { value: 'note-85', label: 'Арка №5' },
    { value: 'note-86', label: 'Арка №6' },
    { value: 'note-87', label: 'Арка №7' },
    { value: 'note-90', label: 'Арка №8' },
    { value: 'note-91', label: 'Арка №9' },
    { value: 'note-92', label: 'Арка №10' },
    { value: 'note-93', label: 'Арка №11' },
    { value: 'note-94', label: 'Корона №1' },
    { value: 'note-95', label: 'Корона №2' },
    { value: 'note-96', label: 'Корона №3' },
    { value: 'note-97', label: 'Корона №4' },
];

export default {
    noteSkat,
    noteClassic,
    note4,
    noteYourDay,
};