export const patina = [
    { value: 'gold', label: 'Золото' },
    { value: 'bronza', label: 'Бронза' },
    { value: 'copper', label: 'Медь' },
    { value: 'champagne', label: 'Шампань' },
    { value: 'silver', label: 'Серебро' },
    { value: 'nut', label: 'Орех' },
    { value: 'brown', label: 'Коричневая' },
    { value: 'beige', label: 'Бежевая' },
    { value: 'blue', label: 'Голубая' },
    { value: 'green', label: 'Зеленая' },
    { value: 'pink', label: 'Розовая' },
    { value: 'white', label: 'Белая' },
    { value: 'lemon', label: 'Лимон' },
    { value: 'lime', label: 'Лайм' },
    { value: 'coral', label: 'Коралловый' },
    { value: 'violet', label: 'Фиолетовый' },
    { value: 'black', label: 'Черный' }, 
];

export const frezEdge = [
    { value: 'BP', label: 'БП (завал без плеча)' },
    { value: 'R3', label: 'R3 (завал без плеча R3)' },
    { value: 'SP', label: 'СП (завал с плечом)' },
    { value: 'R3SP', label: 'R3СП (завал c плечом R3)' },
    { value: 'C', label: 'С (завал со скосом)' },
    { value: 'P', label: 'П (кромка прямая)' },
    { value: 'F', label: 'Ф (кромка фаска)' },
];

export const frez = [
    { value: '001', label: '001' },
    { value: '002', label: '002' },
    { value: '003', label: '003' },
    { value: '004', label: '004' },
    { value: '005', label: '005' },
    { value: '006', label: '006' },
    { value: '007', label: '007' },
    { value: '008', label: '008' },
    { value: '009', label: '009' },
    { value: '010', label: '010' },
    { value: '012', label: '012' },
    { value: '013', label: '013' },
    { value: '014', label: '014' },
    { value: '015', label: '015' },
    { value: '016', label: '016' },
    { value: '017', label: '017' },
    { value: '018', label: '018' },
    { value: '019', label: '019' },
    { value: '020', label: '020' },
    { value: '021', label: '021' },
    { value: '022', label: '022' },
    { value: '023', label: '023' },
    { value: '024', label: '024' },
    { value: '025', label: '025' },
    { value: '026', label: '026' },
    { value: '027', label: '027' },
    { value: '028', label: '028' },
    { value: '029', label: '029' },
    { value: '030', label: '030' },
    { value: '031', label: '031' },
    { value: '032', label: '032' },
    { value: '033', label: '033' },
    { value: '034', label: '034' },
    { value: '035', label: '035' },
    { value: '036', label: '036' },
    { value: '037', label: '037' },
    { value: '038', label: '038' },
    { value: '039', label: '039' },
    { value: '040', label: '040' },
    { value: '041', label: '041' },
    { value: '042', label: '042' },
    { value: '043', label: '043' },
    { value: '044', label: '044' },
    { value: '045', label: '045' },
    { value: '046', label: '046' },
    { value: '047', label: '047' },
    { value: '048', label: '048' },
    { value: '049', label: '049' },
    { value: '050', label: '050' },
    { value: '051', label: '051' },
    { value: '052', label: '052' },
    { value: '053', label: '053' },
    { value: '054', label: '054' },
    { value: '055', label: '055' },
    { value: '056', label: '056' },
    { value: '057', label: '057' },
    { value: '058', label: '058' },
    { value: '059', label: '059' },
    { value: '060', label: '060' },
    { value: '061', label: '061' },
    { value: '062', label: '062' },
    { value: '064', label: '064' },
    { value: '066', label: '066' },
    { value: '067', label: '067' },
    { value: '068', label: '068' },
    { value: '069', label: '069' },
    { value: '070', label: '070' },
    { value: '071', label: '071' },
    { value: '072', label: '072' },
    { value: '073', label: '073' },
    { value: '074', label: '074' },
    { value: '075', label: '075' },
    { value: '076', label: '076' },
    { value: '077', label: '077' },
    { value: '078', label: '078' },
    { value: '079', label: '079' },
    { value: '079/1', label: '079/1' },
    { value: '080', label: '080' },
    { value: '082/21', label: '082/21' },
    { value: '082', label: '082' },
    { value: '083', label: '083' },
    { value: '084', label: '084' },
    { value: '085', label: '085' },
    { value: '086', label: '086' },
    { value: '087', label: '087 ' }, 
    { value: '087/1', label: '087/1' },
    { value: '088', label: '088' },
    { value: '089', label: '089' },
    { value: '090', label: '090' },
    { value: '091', label: '091' },
    { value: '092', label: '092' },
    { value: '093', label: '093' },
    { value: '094', label: '094' },
    { value: '095', label: '095' },
    { value: '096', label: '096' },
    { value: '097', label: '097' },
    { value: '098', label: '098' },
    { value: '101', label: '101' },
    { value: '102', label: '102' },
    { value: '103', label: '103' },
    { value: '104', label: '104' },
    { value: '105', label: '105' },
    { value: '106', label: '106' },
    { value: '106/1', label: '106/1' },
    { value: '107', label: '107' },
    { value: '108/1', label: '108/1' },
    { value: '108/2', label: '108/2' },
    { value: '108/3', label: '108/3' },
    { value: '109', label: '109' },
    { value: '110', label: '110' },
    { value: '201 тип 1', label: '201 тип 1' },
    { value: '201 тип 2', label: '201 тип 2' },
    { value: '201 тип 3', label: '201 тип 3' },
    { value: '202 тип 1', label: '202 тип 1' },
    { value: '202 тип 2', label: '202 тип 2' },
    { value: '202 тип 3', label: '202 тип 3' }, 
    { value: '301', label: '301' },
    { value: '302', label: '302' },
    { value: '303', label: '303' },
    { value: '304', label: '304' },
    { value: '305', label: '305' },
    { value: '306', label: '306' },
    { value: '307', label: '307' },
    { value: '308', label: '308' },
    { value: '309', label: '309' },
    { value: '310', label: '310' },
    { value: '400', label: '400' },
    { value: '401', label: '401' },
    { value: '402', label: '402' },
    { value: '403', label: '403' },
    { value: '404', label: '404' },
    { value: '405', label: '405 ' }, 
    { value: '80/1', label: '80/1' },
    { value: '89', label: '89' },
    { value: '99', label: '99' },
];

export const color = [
    { optgroup: '1 категория' },
    { value: '1k-1', label: '5029-43 1к.' },
    { value: '1k-2', label: 'белая шагрень ' },
    { value: '1k-3', label: 'белое дерево 1к.' },
    { value: '1k-4', label: 'бук 1к.' },
    { value: '1k-5', label: 'ваниль 1к.' },
    { value: '1k-6', label: 'венге 1к.' },
    { value: '1k-7', label: 'венге светлый 1к.' },
    { value: '1k-8', label: 'выбеленный дуб 1к.' },
    { value: '1k-9', label: 'голубое небо 1к.' },
    { value: '1k-10', label: 'дуб антик 1к.' },
    { value: '1k-11', label: 'дуб коричневый 1к.' },
    { value: '1k-12', label: 'дуб крафт белый 1к.' },
    { value: '1k-13', label: 'дуб крафт серый 1к.' },
    { value: '1k-14', label: 'дуб крафт табачный' },
    { value: '1k-15', label: 'дуб сокальский 1к.' },
    { value: '1k-16', label: 'дуб крымский 1к.' },
    { value: '1k-17', label: 'дуб тортуга 1к.' },
    { value: '1k-18', label: 'ель 1к.' },
    { value: '1k-19', label: 'кантри венге 1к.' },
    { value: '1k-20', label: 'клен Азия 1к.' },
    { value: '1k-21', label: 'кокос белый 1к.' },
    { value: '1k-22', label: 'лиственница светлая 1 к' },
    { value: '1k-23', label: 'орех 42 1к.' },
    { value: '1k-24', label: 'орех миланский 1к.' },
    { value: '1k-25', label: 'ореховый дубослив 1к.' },
    { value: '1k-26', label: 'реалвуд грей 1к.' },
    { value: '1k-27', label: 'реалвуд фисташка 1к.' },
    { value: '1k-28', label: 'реалвуд шалфей 1к.' },
    { value: '1k-29', label: 'сандал белый 1к.' },
    { value: '1k-30', label: 'сандал серый 1к.' },
    { value: '1k-31', label: 'санторини белый 1к.' },
    { value: '1k-32', label: 'санторини черный 1к.' },
    { value: '1k-33', label: 'скандинавский дуб белый 1к.' },
    { value: '1k-34', label: 'скандинавский дуб серый 1к.' },
    { value: '1k-35', label: 'сосна белая 1к.' },
    { value: '1k-36', label: 'сталь 1к.' },
    { value: '1k-37', label: 'старое дерево 1к.' },
    { value: '1k-38', label: 'тиковое дерево 1к.' },
    { value: '1k-39', label: 'черная шагрень 1к.' },
    { value: '1k-40', label: 'дуб сиена карамельный 1к.' },
    { optgroup: '2 категория' },
    { value: '2k-1', label: 'бетон арья 2к.' },
    { value: '2k-2', label: 'бетон беж 2к.' },
    { value: '2k-3', label: 'бетон графит 2к.' },
    { value: '2k-4', label: 'бетон дрого 2к.' },
    { value: '2k-5', label: 'бетон натуральный 2к.' },
    { value: '2k-6', label: 'бетон оленна 2к.' },
    { value: '2k-7', label: 'бетон серсея 2к.' },
    { value: '2k-8', label: 'бетон Хафит 2к.' },
    { value: '2k-9', label: 'дуб агат 2к.' },
    { value: '2k-10', label: 'дуб болотный 2к.' },
    { value: '2k-11', label: 'дуб бомонт натуральный 2к.' },
    { value: '2k-12', label: 'дуб винтаж графит 2к.' },
    { value: '2k-13', label: 'дуб винтаж грей 2к.' },
    { value: '2k-14', label: 'дуб винтаж медовый 2к.' },
    { value: '2k-15', label: 'дуб деним 2к.' },
    { value: '2k-16', label: 'дуб кварц 2к.' },
    { value: '2k-17', label: 'дуб мелфорд 2к.' },
    { value: '2k-18', label: 'дуб мелфорд светлый 2к.' },
    { value: '2k-19', label: 'дуб мокко 2к.' },
    { value: '2k-20', label: 'дуб полярный 2к.' },
    { value: '2k-21', label: 'дуб седой 2к.' },
    { value: '2k-22', label: 'дуб снежный 2к.' },
    { value: '2k-23', label: 'дуб чернильный 2к.' },
    { value: '2k-24', label: 'дуб честерфилд 2к.' },
    { value: '2k-25', label: 'дюна мистраль 2к.' },
    { value: '2k-26', label: 'дюна муссон 2к.' },
    { value: '2k-27', label: 'дюна солано 2к.' },
    { value: '2k-28', label: 'золотой ясень 2к.' },
    { value: '2k-29', label: 'изумрудное дерево 2к.' },
    { value: '2k-30', label: 'крем ясень под патину 2к.' },
    { value: '2k-31', label: 'крымской дерево 2к.' },
    { value: '2k-32', label: 'структурный белый 2к.' },
    { value: '2k-33', label: 'лазурное дерево 2к.' },
    { value: '2k-34', label: 'мармарино белый 2к.' },
    { value: '2k-35', label: 'мармарино грей 2к.' },
    { value: '2k-36', label: 'мармарино капучино 2к.' },
    { value: '2k-37', label: 'мармарино черный 2к.' },
    { value: '2k-38', label: 'мрамор светлый 2к.' },
    { value: '2k-39', label: 'мрамор темно серый 2к.' },
    { value: '2k-40', label: 'мрамор черный 2к.' },
    { value: '2k-41', label: 'патина белый снег 2к.' },
    { value: '2k-42', label: 'патина голубая 2к.' },
    { value: '2k-43', label: 'патина миртовая 2к.' },
    { value: '2k-44', label: 'сканди жасмин 2к.' },
    { value: '2k-45', label: 'сканди имбирь 2к.' },
    { value: '2k-46', label: 'сканди мускат 2к.' },
    { value: '2k-47', label: 'снег шагрень 2к.' },
    { value: '2k-48', label: 'сосна скания светлая 2к.' },
    { value: '2k-49', label: 'сосна скания темная 2к.' },
    { value: '2k-50', label: 'структурный белый 2к.' },
    { value: '2k-51', label: 'тангент перламутр 2к.' },
    { value: '2k-52', label: 'шато крем 2к.' },
    { value: '2k-53', label: 'шоколад 2к.' },
    { value: '2k-54', label: 'ясень жемчужный 2к.' },
    { value: '2k-55', label: 'версилк айс 2к' },
    { value: '2k-56', label: 'версилк крем 2 к.' },
    { value: '2k-57', label: 'версилк грей 2 к' },
    { value: '2k-58', label: 'версилк графит 2 к' },
    { value: '2k-59', label: 'Сканди графит 2к' },
    { value: '2k-60', label: 'Сканди тмин 2к' },
    { optgroup: '3 категория' },
    { value: '3k-1', label: 'бежевый глянец 3к.' },
    { value: '3k-2', label: 'белый глянец 3к.' },
    { value: '3k-3', label: 'бордо глянец 3к.' },
    { value: '3k-4', label: 'ваниль глянец 3к.' },
    { value: '3k-5', label: 'дуб сонома 3к. ' },
    { value: '3k-6', label: 'желтый глянец 3к.' },
    { value: '3k-7', label: 'кофе глянец 3к.' },
    { value: '3k-8', label: 'мелисандра 3к.' },
    { value: '3k-9', label: 'орех классический 3к.' },
    { value: '3k-10', label: 'орех натуральный 3к.' },
    { value: '3k-11', label: 'орех мокко 3к.' },
    { value: '3k-12', label: 'титан глянец 3к. ' },
    { value: '3k-13', label: 'слоновая кость глянец 3к.' },
    { value: '3k-14', label: 'черный глянец 3к.' },
    { value: '3k-15', label: 'Монте антик 3 к' },
    { value: '3k-16', label: 'Монте тиберио  3 к ' },
    { optgroup: '4 категория' },
    { value: '4k-1', label: '302 4к.' },
    { value: '4k-2', label: 'белый металлик 4к.' },
    { value: '4k-3', label: 'капучино металлик 4к.' },
    { value: '4k-4', label: 'огни Нью-Йорка белые 4к.' },
    { value: '4k-5', label: 'огни Нью-Йорка черные 4к.' },
    { value: '4k-6', label: 'серебро 4к.' },
    { value: '4k-7', label: 'сиреневый металлик 4к.' },
    { value: '4k-8', label: 'черный металлик 4к.' },
    { value: '4k-9', label: 'шампань 4к.' },
    { value: '4k-10', label: 'шоколад металлик 4к' },
    { value: '4k-11', label: 'макиоти металлик 4 к.' },
    { value: '4k-12', label: 'глянец мрамор WHITE 4к.' },
    { value: '4k-13', label: 'глянец мрамор BLACK 4к.' },
    { optgroup: 'Софт' },
    { value: 'soft-1', label: 'альвиано матовый 3 к ' },
    { value: 'soft-2', label: 'антарктида матовый 3к.' },
    { value: 'soft-3', label: 'беж нубук 3к.' },
    { value: 'soft-4', label: 'бежевый софт 3к. ' },
    { value: 'soft-5', label: 'берлин мат. 3к.' },
    { value: 'soft-6', label: 'болотный софт 3к.' },
    { value: 'soft-7', label: 'больсена матовый 3к.' },
    { value: 'soft-8', label: 'браччано матовый 3к.' },
    { value: 'soft-9', label: 'бриз софт 3к. ' },
    { value: 'soft-10', label: 'гарлате матовый 3к.' },
    { value: 'soft-11', label: 'голубой софт 3к.' },
    { value: 'soft-12', label: 'графит мат. 3к.' },
    { value: 'soft-13', label: 'грей нубук 3к.' },
    { value: 'soft-14', label: 'денвер мат. 3к.' },
    { value: 'soft-15', label: 'идро матовый 3к.' },
    { value: 'soft-16', label: 'комо матовый 3к.' },
    { value: 'soft-17', label: 'лезина матовый 3к.' },
    { value: 'soft-18', label: 'лиловый софт 3к.' },
    { value: 'soft-19', label: 'магнолия мат. 3к. ' },
    { value: 'soft-20', label: 'манила мат. 3к.' },
    { value: 'soft-21', label: 'мантова матовый 3к.' },
    { value: 'soft-22', label: 'миррис матовый 3к.' },
    { value: 'soft-23', label: 'мокко матовый 3к.' },
    { value: 'soft-24', label: 'нефрит матовый 3к.' },
    { value: 'soft-25', label: 'обсидиан матовый 3к.' },
    { value: 'soft-26', label: 'олива софт 3к.' },
    { value: 'soft-27', label: 'оливин 3к.' },
    { value: 'soft-28', label: 'орта матовый 3к.' },
    { value: 'soft-29', label: 'резия матовый 3к.' },
    { value: 'soft-30', label: 'сагаста мат. 3к.' },
    { value: 'soft-31', label: 'селемит матовый 3к.' },
    { value: 'soft-32', label: 'серый софт 3к.' },
    { value: 'soft-33', label: 'софт белый 3к.' },
    { value: 'soft-34', label: 'софт грей 3к.' },
    { value: 'soft-35', label: 'софт черный 3к.' },
    { value: 'soft-36', label: 'темно-синий софт 3к.' },
    { value: 'soft-37', label: 'фисташковый софт 3к. ' },
    { value: 'soft-38', label: 'шоколад мат. 3к.' },
    { value: 'soft-39', label: 'Амарок 3к' },
    { value: 'soft-40', label: 'Биланчино 3к ' },
    { value: 'soft-41', label: 'Красная Бургундия 3к ' },
    { value: 'soft-42', label: 'Красно-коричневый 3к' },
    { value: 'soft-43', label: 'Лаййт Хаки 3 к ' },
    { value: 'soft-44', label: 'Маренго 3к' },
    { value: 'soft-45', label: 'Пудровый 3к' },
    { value: 'soft-46', label: 'Смоук 3к ' },
    { value: 'soft-47', label: 'Терракот 3 к' },
    { value: 'soft-48', label: 'Фонди 3 к' },
    { value: 'soft-49', label: 'Эвкалипт 3к' },
];
 export default {
    patina,
    frezEdge,
    color,
    frez,
};